### ISSUE TITLE
Monorepo [Turborepo]

### ISSUE THREAD

**Issue by maxval1** [kevincobain2000/action-cache-http#16]
Can you provide an example of how to cache subfolder `node_modules` in Monorepo ?
When we have:

```
Root
package.json
package-lock.json // (1)
node_modules

  | -- Package1
        package.json
        node_modules // <- how i can cache (this node_modules depends of package-lock.json(1))

  | -- Package2
        package.json
        node_modules // <- how i can cache  (this node_modules depends of package-lock.json(1))

  | -- Other Packages
```

**Comment by kevincobain2000** [comment]
There is an option `operating_dir: "./" # optional` in the README, which should do what you are looking for.

**Comment by maxval1** [comment]
> There is an option `operating_dir: "./" # optional` in the README, which should do what you are looking for.

```
      - name: Install Dependencies
        uses: kevincobain2000/action-cache-http@v3
        with:
          version: 18
          lock_file: package-lock.json
          install_command: npm install
          operating_dir: "./" // root dir
          destination_folder: **/node_modules // all node_modules in all subdirectories 
          cache_http_api: "http://cache-http"
```
