### ISSUE TITLE
Issues with nested directories

### ISSUE THREAD

**Issue by slaughtr** [kevincobain2000/action-cache-http#2]
Hello, trying to get this working with a project that has multip sub-directories with lock files etc. Running into issues finding the lock files with the default setup, but also when using any combination of relative/absolute pathing. 

General setup:

```
      - name: Yarn Install (with cache)
        uses: kevincobain2000/action-cache-http@v2
        with:
          version: 14
          lock_file: yarn.lock
          install_command: cd infra && yarn install
          destination_folder: node_modules
          cache_http_api: "http://172.17.0.1:3000/cache-http"
          http_proxy: ""
```

Getting the following error:

```
##[group]Run kevincobain2000/action-cache-http@v2
with:
  version: 14
  lock_file: yarn.lock
  install_command: yarn install
  destination_folder: node_modules
  cache_http_api: http://172.17.0.1:3000/cache-http
env:
  NODE_ENV: test
##[endgroup]
##[command]/usr/bin/docker exec  f502a4b5c0371f46515212c324d00451d643784eaabbddec19b547cd439ac08c sh -c "cat /etc/*release | grep ^ID"
Error: Command failed: /__w/_actions/kevincobain2000/action-cache-http/v2/cache-http.sh
yarn.lock: No such file or directory
tar: node_modules: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
 1: 0x9da7c0 node::Abort() [/__e/node12/bin/node]
  killed: false,
  code: 2,
  signal: null,
  cmd: '/__w/_actions/kevincobain2000/action-cache-http/v2/cache-http.sh'
}
 2: 0xa4e219  [/__e/node12/bin/node]
 3: 0xba5d59  [/__e/node12/bin/node]
 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/__e/node12/bin/node]
 5: 0x13750d9  [/__e/node12/bin/node]
 ```
 
 Seems the server is working as it should, and as mentioned I've tried every combination of `lock_file` imaginable: `subdir/yarn.lock` - `yarn.lock` - `/full/path/to/subdir/yarn.lock` - `$(cwd)/yarn.lock` - nothing works.
 
 I also tried using the README from the root of the project to see if that would work and while it did find the README, it `yarn install`'d in the root (I believe) which failed because that's not actually the right place. So the issue does seem to be that subdirectories aren't where the action is running from, despite that being the `working-directory` for the job.
 
 Any suggestions welcome, this would be very helpful for us. Thanks!

**Comment by kevincobain2000** [comment]
Hi, unfortunately, it doesn't support dir change.
What you can do however with some extra steps.

```
- name: Pre install
  run: |
    cp infra/package.json ./
    cp infra/yarn.lock ./

- name: Yarn Install (with cache)
  uses: kevincobain2000/action-cache-http@v2
  with:
    version: 14
    lock_file: yarn.lock
    install_command: yarn install
    destination_folder: node_modules
    cache_http_api: "http://172.17.0.1:3000/cache-http"
    http_proxy: ""

- name: Post install
  run: |
    rm -rf infra/node_modules
    mv node_modules infra/node_modules
    rm yarn.lock package.json
```
